# Generated by Django 6.0.5 on 2026-07-05 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_lesson_deep_dive_md'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🧭', help_text='Emoji for the timeline node', max_length=8)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('est_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('learn_md', models.TextField(blank=True, help_text='What to learn in this stage')),
                ('build_md', models.TextField(blank=True, help_text='Hands-on things to build')),
                ('done_when_md', models.TextField(blank=True, help_text="Self-check: you're done when…")),
                ('order', models.PositiveIntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, related_name='roadmap_stages', to='catalog.course')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Done')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='roadmap.roadmapstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stage')},
            },
        ),
    ]
