# Generated by Django 6.0.5 on 2026-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deep_dive_md',
            field=models.TextField(blank=True, help_text="Optional 'Under the hood' OS-level deep dive"),
        ),
    ]
